// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// PatchProvisioningV1InternalAccountsOrgIDProviderReader is a Reader for the PatchProvisioningV1InternalAccountsOrgIDProvider structure.
type PatchProvisioningV1InternalAccountsOrgIDProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchProvisioningV1InternalAccountsOrgIDProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPatchProvisioningV1InternalAccountsOrgIDProviderNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchProvisioningV1InternalAccountsOrgIDProviderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchProvisioningV1InternalAccountsOrgIDProviderNoContent creates a PatchProvisioningV1InternalAccountsOrgIDProviderNoContent with default headers values
func NewPatchProvisioningV1InternalAccountsOrgIDProviderNoContent() *PatchProvisioningV1InternalAccountsOrgIDProviderNoContent {
	return &PatchProvisioningV1InternalAccountsOrgIDProviderNoContent{}
}

/* PatchProvisioningV1InternalAccountsOrgIDProviderNoContent describes a response with status code 204, with default header values.

No Content
*/
type PatchProvisioningV1InternalAccountsOrgIDProviderNoContent struct {
}

func (o *PatchProvisioningV1InternalAccountsOrgIDProviderNoContent) Error() string {
	return fmt.Sprintf("[PATCH /provisioning/v1/internal/accounts/{org_id}/{provider}][%d] patchProvisioningV1InternalAccountsOrgIdProviderNoContent ", 204)
}

func (o *PatchProvisioningV1InternalAccountsOrgIDProviderNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchProvisioningV1InternalAccountsOrgIDProviderBadRequest creates a PatchProvisioningV1InternalAccountsOrgIDProviderBadRequest with default headers values
func NewPatchProvisioningV1InternalAccountsOrgIDProviderBadRequest() *PatchProvisioningV1InternalAccountsOrgIDProviderBadRequest {
	return &PatchProvisioningV1InternalAccountsOrgIDProviderBadRequest{}
}

/* PatchProvisioningV1InternalAccountsOrgIDProviderBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PatchProvisioningV1InternalAccountsOrgIDProviderBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *PatchProvisioningV1InternalAccountsOrgIDProviderBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /provisioning/v1/internal/accounts/{org_id}/{provider}][%d] patchProvisioningV1InternalAccountsOrgIdProviderBadRequest  %+v", 400, o.Payload)
}
func (o *PatchProvisioningV1InternalAccountsOrgIDProviderBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *PatchProvisioningV1InternalAccountsOrgIDProviderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError creates a PatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError with default headers values
func NewPatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError() *PatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError {
	return &PatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError{}
}

/* PatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *PatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /provisioning/v1/internal/accounts/{org_id}/{provider}][%d] patchProvisioningV1InternalAccountsOrgIdProviderInternalServerError  %+v", 500, o.Payload)
}
func (o *PatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *PatchProvisioningV1InternalAccountsOrgIDProviderInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
