// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// PostProvisioningV1InternalAccountsReader is a Reader for the PostProvisioningV1InternalAccounts structure.
type PostProvisioningV1InternalAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProvisioningV1InternalAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostProvisioningV1InternalAccountsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostProvisioningV1InternalAccountsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostProvisioningV1InternalAccountsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostProvisioningV1InternalAccountsCreated creates a PostProvisioningV1InternalAccountsCreated with default headers values
func NewPostProvisioningV1InternalAccountsCreated() *PostProvisioningV1InternalAccountsCreated {
	return &PostProvisioningV1InternalAccountsCreated{}
}

/* PostProvisioningV1InternalAccountsCreated describes a response with status code 201, with default header values.

Created
*/
type PostProvisioningV1InternalAccountsCreated struct {
	Payload *models.V1AccountResponse
}

func (o *PostProvisioningV1InternalAccountsCreated) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/internal/accounts][%d] postProvisioningV1InternalAccountsCreated  %+v", 201, o.Payload)
}
func (o *PostProvisioningV1InternalAccountsCreated) GetPayload() *models.V1AccountResponse {
	return o.Payload
}

func (o *PostProvisioningV1InternalAccountsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1AccountResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostProvisioningV1InternalAccountsBadRequest creates a PostProvisioningV1InternalAccountsBadRequest with default headers values
func NewPostProvisioningV1InternalAccountsBadRequest() *PostProvisioningV1InternalAccountsBadRequest {
	return &PostProvisioningV1InternalAccountsBadRequest{}
}

/* PostProvisioningV1InternalAccountsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostProvisioningV1InternalAccountsBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *PostProvisioningV1InternalAccountsBadRequest) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/internal/accounts][%d] postProvisioningV1InternalAccountsBadRequest  %+v", 400, o.Payload)
}
func (o *PostProvisioningV1InternalAccountsBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *PostProvisioningV1InternalAccountsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostProvisioningV1InternalAccountsInternalServerError creates a PostProvisioningV1InternalAccountsInternalServerError with default headers values
func NewPostProvisioningV1InternalAccountsInternalServerError() *PostProvisioningV1InternalAccountsInternalServerError {
	return &PostProvisioningV1InternalAccountsInternalServerError{}
}

/* PostProvisioningV1InternalAccountsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostProvisioningV1InternalAccountsInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *PostProvisioningV1InternalAccountsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/internal/accounts][%d] postProvisioningV1InternalAccountsInternalServerError  %+v", 500, o.Payload)
}
func (o *PostProvisioningV1InternalAccountsInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *PostProvisioningV1InternalAccountsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
