// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/client/accounts"
	"github.com/mariadb-corporation/skysql-api-go/v2/dps/client/clusters"
	"github.com/mariadb-corporation/skysql-api-go/v2/dps/client/config"
	"github.com/mariadb-corporation/skysql-api-go/v2/dps/client/offering"
	"github.com/mariadb-corporation/skysql-api-go/v2/dps/client/products"
	"github.com/mariadb-corporation/skysql-api-go/v2/dps/client/services"
	"github.com/mariadb-corporation/skysql-api-go/v2/dps/client/services_security"
)

// Default dps HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8080"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new dps HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Dps {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new dps HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Dps {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new dps client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Dps {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Dps)
	cli.Transport = transport
	cli.Accounts = accounts.New(transport, formats)
	cli.Clusters = clusters.New(transport, formats)
	cli.Config = config.New(transport, formats)
	cli.Offering = offering.New(transport, formats)
	cli.Products = products.New(transport, formats)
	cli.Services = services.New(transport, formats)
	cli.ServicesSecurity = services_security.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Dps is a client for dps
type Dps struct {
	Accounts accounts.ClientService

	Clusters clusters.ClientService

	Config config.ClientService

	Offering offering.ClientService

	Products products.ClientService

	Services services.ClientService

	ServicesSecurity services_security.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Dps) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Accounts.SetTransport(transport)
	c.Clusters.SetTransport(transport)
	c.Config.SetTransport(transport)
	c.Offering.SetTransport(transport)
	c.Products.SetTransport(transport)
	c.Services.SetTransport(transport)
	c.ServicesSecurity.SetTransport(transport)
}
