/*
SkySQL API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skysql

import (
	"encoding/json"
)

// NewConfigurationResponse New Configuration Response
type NewConfigurationResponse struct {
	Number string `json:"number"`
	Topology string `json:"topology"`
	SysModCount string `json:"sys_mod_count"`
	Active string `json:"active"`
	Project string `json:"project"`
	OwnedBy string `json:"owned_by"`
	SysUpdatedOn string `json:"sys_updated_on"`
	SysTags string `json:"sys_tags"`
	SysId string `json:"sys_id"`
	SysUpdatedBy string `json:"sys_updated_by"`
	Public string `json:"public"`
	SysCreatedOn string `json:"sys_created_on"`
	Name string `json:"name"`
	SysCreatedBy string `json:"sys_created_by"`
	ConfigurationVersion ConfigurationVersion `json:"configuration_version"`
}

// NewNewConfigurationResponse instantiates a new NewConfigurationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewConfigurationResponse(number string, topology string, sysModCount string, active string, project string, ownedBy string, sysUpdatedOn string, sysTags string, sysId string, sysUpdatedBy string, public string, sysCreatedOn string, name string, sysCreatedBy string, configurationVersion ConfigurationVersion) *NewConfigurationResponse {
	this := NewConfigurationResponse{}
	this.Number = number
	this.Topology = topology
	this.SysModCount = sysModCount
	this.Active = active
	this.Project = project
	this.OwnedBy = ownedBy
	this.SysUpdatedOn = sysUpdatedOn
	this.SysTags = sysTags
	this.SysId = sysId
	this.SysUpdatedBy = sysUpdatedBy
	this.Public = public
	this.SysCreatedOn = sysCreatedOn
	this.Name = name
	this.SysCreatedBy = sysCreatedBy
	this.ConfigurationVersion = configurationVersion
	return &this
}

// NewNewConfigurationResponseWithDefaults instantiates a new NewConfigurationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewConfigurationResponseWithDefaults() *NewConfigurationResponse {
	this := NewConfigurationResponse{}
	return &this
}

// GetNumber returns the Number field value
func (o *NewConfigurationResponse) GetNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *NewConfigurationResponse) SetNumber(v string) {
	o.Number = v
}

// GetTopology returns the Topology field value
func (o *NewConfigurationResponse) GetTopology() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Topology
}

// GetTopologyOk returns a tuple with the Topology field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetTopologyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Topology, true
}

// SetTopology sets field value
func (o *NewConfigurationResponse) SetTopology(v string) {
	o.Topology = v
}

// GetSysModCount returns the SysModCount field value
func (o *NewConfigurationResponse) GetSysModCount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysModCount
}

// GetSysModCountOk returns a tuple with the SysModCount field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetSysModCountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysModCount, true
}

// SetSysModCount sets field value
func (o *NewConfigurationResponse) SetSysModCount(v string) {
	o.SysModCount = v
}

// GetActive returns the Active field value
func (o *NewConfigurationResponse) GetActive() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetActiveOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *NewConfigurationResponse) SetActive(v string) {
	o.Active = v
}

// GetProject returns the Project field value
func (o *NewConfigurationResponse) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetProjectOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *NewConfigurationResponse) SetProject(v string) {
	o.Project = v
}

// GetOwnedBy returns the OwnedBy field value
func (o *NewConfigurationResponse) GetOwnedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnedBy
}

// GetOwnedByOk returns a tuple with the OwnedBy field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetOwnedByOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OwnedBy, true
}

// SetOwnedBy sets field value
func (o *NewConfigurationResponse) SetOwnedBy(v string) {
	o.OwnedBy = v
}

// GetSysUpdatedOn returns the SysUpdatedOn field value
func (o *NewConfigurationResponse) GetSysUpdatedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysUpdatedOn
}

// GetSysUpdatedOnOk returns a tuple with the SysUpdatedOn field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetSysUpdatedOnOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysUpdatedOn, true
}

// SetSysUpdatedOn sets field value
func (o *NewConfigurationResponse) SetSysUpdatedOn(v string) {
	o.SysUpdatedOn = v
}

// GetSysTags returns the SysTags field value
func (o *NewConfigurationResponse) GetSysTags() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysTags
}

// GetSysTagsOk returns a tuple with the SysTags field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetSysTagsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysTags, true
}

// SetSysTags sets field value
func (o *NewConfigurationResponse) SetSysTags(v string) {
	o.SysTags = v
}

// GetSysId returns the SysId field value
func (o *NewConfigurationResponse) GetSysId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysId
}

// GetSysIdOk returns a tuple with the SysId field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetSysIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysId, true
}

// SetSysId sets field value
func (o *NewConfigurationResponse) SetSysId(v string) {
	o.SysId = v
}

// GetSysUpdatedBy returns the SysUpdatedBy field value
func (o *NewConfigurationResponse) GetSysUpdatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysUpdatedBy
}

// GetSysUpdatedByOk returns a tuple with the SysUpdatedBy field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetSysUpdatedByOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysUpdatedBy, true
}

// SetSysUpdatedBy sets field value
func (o *NewConfigurationResponse) SetSysUpdatedBy(v string) {
	o.SysUpdatedBy = v
}

// GetPublic returns the Public field value
func (o *NewConfigurationResponse) GetPublic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Public
}

// GetPublicOk returns a tuple with the Public field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetPublicOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Public, true
}

// SetPublic sets field value
func (o *NewConfigurationResponse) SetPublic(v string) {
	o.Public = v
}

// GetSysCreatedOn returns the SysCreatedOn field value
func (o *NewConfigurationResponse) GetSysCreatedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysCreatedOn
}

// GetSysCreatedOnOk returns a tuple with the SysCreatedOn field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetSysCreatedOnOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysCreatedOn, true
}

// SetSysCreatedOn sets field value
func (o *NewConfigurationResponse) SetSysCreatedOn(v string) {
	o.SysCreatedOn = v
}

// GetName returns the Name field value
func (o *NewConfigurationResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NewConfigurationResponse) SetName(v string) {
	o.Name = v
}

// GetSysCreatedBy returns the SysCreatedBy field value
func (o *NewConfigurationResponse) GetSysCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysCreatedBy
}

// GetSysCreatedByOk returns a tuple with the SysCreatedBy field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetSysCreatedByOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysCreatedBy, true
}

// SetSysCreatedBy sets field value
func (o *NewConfigurationResponse) SetSysCreatedBy(v string) {
	o.SysCreatedBy = v
}

// GetConfigurationVersion returns the ConfigurationVersion field value
func (o *NewConfigurationResponse) GetConfigurationVersion() ConfigurationVersion {
	if o == nil {
		var ret ConfigurationVersion
		return ret
	}

	return o.ConfigurationVersion
}

// GetConfigurationVersionOk returns a tuple with the ConfigurationVersion field value
// and a boolean to check if the value has been set.
func (o *NewConfigurationResponse) GetConfigurationVersionOk() (*ConfigurationVersion, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ConfigurationVersion, true
}

// SetConfigurationVersion sets field value
func (o *NewConfigurationResponse) SetConfigurationVersion(v ConfigurationVersion) {
	o.ConfigurationVersion = v
}

func (o NewConfigurationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["number"] = o.Number
	}
	if true {
		toSerialize["topology"] = o.Topology
	}
	if true {
		toSerialize["sys_mod_count"] = o.SysModCount
	}
	if true {
		toSerialize["active"] = o.Active
	}
	if true {
		toSerialize["project"] = o.Project
	}
	if true {
		toSerialize["owned_by"] = o.OwnedBy
	}
	if true {
		toSerialize["sys_updated_on"] = o.SysUpdatedOn
	}
	if true {
		toSerialize["sys_tags"] = o.SysTags
	}
	if true {
		toSerialize["sys_id"] = o.SysId
	}
	if true {
		toSerialize["sys_updated_by"] = o.SysUpdatedBy
	}
	if true {
		toSerialize["public"] = o.Public
	}
	if true {
		toSerialize["sys_created_on"] = o.SysCreatedOn
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["sys_created_by"] = o.SysCreatedBy
	}
	if true {
		toSerialize["configuration_version"] = o.ConfigurationVersion
	}
	return json.Marshal(toSerialize)
}

type NullableNewConfigurationResponse struct {
	value *NewConfigurationResponse
	isSet bool
}

func (v NullableNewConfigurationResponse) Get() *NewConfigurationResponse {
	return v.value
}

func (v *NullableNewConfigurationResponse) Set(val *NewConfigurationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNewConfigurationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNewConfigurationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewConfigurationResponse(val *NewConfigurationResponse) *NullableNewConfigurationResponse {
	return &NullableNewConfigurationResponse{value: val, isSet: true}
}

func (v NullableNewConfigurationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewConfigurationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


