/*
SkySQL API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package skysql

import (
	"encoding/json"
)

// Topology Cluster topology valid for a particular product, e.g. Standalone or MaxScale
type Topology struct {
	MaxscaleSupported string `json:"maxscale_supported"`
	OperatorReplicaMinimum string `json:"operator_replica_minimum"`
	Product string `json:"product"`
	ReplicaOptions string `json:"replica_options"`
	SysModCount string `json:"sys_mod_count"`
	Active string `json:"active"`
	SysUpdatedOn string `json:"sys_updated_on"`
	DisplayName string `json:"display_name"`
	SysTags string `json:"sys_tags"`
	SysId string `json:"sys_id"`
	HasReplicas string `json:"has_replicas"`
	SysUpdatedBy string `json:"sys_updated_by"`
	HasClustrixFrontend string `json:"has_clustrix_frontend"`
	SysCreatedOn string `json:"sys_created_on"`
	Name string `json:"name"`
	Paid string `json:"paid"`
	ReplicaLabel string `json:"replica_label"`
	MariadbCronbackEnabled string `json:"mariadb_cronback_enabled"`
	Value string `json:"value"`
	SysCreatedBy string `json:"sys_created_by"`
	ApiHandle string `json:"api_handle"`
}

// NewTopology instantiates a new Topology object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopology(maxscaleSupported string, operatorReplicaMinimum string, product string, replicaOptions string, sysModCount string, active string, sysUpdatedOn string, displayName string, sysTags string, sysId string, hasReplicas string, sysUpdatedBy string, hasClustrixFrontend string, sysCreatedOn string, name string, paid string, replicaLabel string, mariadbCronbackEnabled string, value string, sysCreatedBy string, apiHandle string) *Topology {
	this := Topology{}
	this.MaxscaleSupported = maxscaleSupported
	this.OperatorReplicaMinimum = operatorReplicaMinimum
	this.Product = product
	this.ReplicaOptions = replicaOptions
	this.SysModCount = sysModCount
	this.Active = active
	this.SysUpdatedOn = sysUpdatedOn
	this.DisplayName = displayName
	this.SysTags = sysTags
	this.SysId = sysId
	this.HasReplicas = hasReplicas
	this.SysUpdatedBy = sysUpdatedBy
	this.HasClustrixFrontend = hasClustrixFrontend
	this.SysCreatedOn = sysCreatedOn
	this.Name = name
	this.Paid = paid
	this.ReplicaLabel = replicaLabel
	this.MariadbCronbackEnabled = mariadbCronbackEnabled
	this.Value = value
	this.SysCreatedBy = sysCreatedBy
	this.ApiHandle = apiHandle
	return &this
}

// NewTopologyWithDefaults instantiates a new Topology object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopologyWithDefaults() *Topology {
	this := Topology{}
	return &this
}

// GetMaxscaleSupported returns the MaxscaleSupported field value
func (o *Topology) GetMaxscaleSupported() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxscaleSupported
}

// GetMaxscaleSupportedOk returns a tuple with the MaxscaleSupported field value
// and a boolean to check if the value has been set.
func (o *Topology) GetMaxscaleSupportedOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MaxscaleSupported, true
}

// SetMaxscaleSupported sets field value
func (o *Topology) SetMaxscaleSupported(v string) {
	o.MaxscaleSupported = v
}

// GetOperatorReplicaMinimum returns the OperatorReplicaMinimum field value
func (o *Topology) GetOperatorReplicaMinimum() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperatorReplicaMinimum
}

// GetOperatorReplicaMinimumOk returns a tuple with the OperatorReplicaMinimum field value
// and a boolean to check if the value has been set.
func (o *Topology) GetOperatorReplicaMinimumOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OperatorReplicaMinimum, true
}

// SetOperatorReplicaMinimum sets field value
func (o *Topology) SetOperatorReplicaMinimum(v string) {
	o.OperatorReplicaMinimum = v
}

// GetProduct returns the Product field value
func (o *Topology) GetProduct() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Product
}

// GetProductOk returns a tuple with the Product field value
// and a boolean to check if the value has been set.
func (o *Topology) GetProductOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Product, true
}

// SetProduct sets field value
func (o *Topology) SetProduct(v string) {
	o.Product = v
}

// GetReplicaOptions returns the ReplicaOptions field value
func (o *Topology) GetReplicaOptions() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReplicaOptions
}

// GetReplicaOptionsOk returns a tuple with the ReplicaOptions field value
// and a boolean to check if the value has been set.
func (o *Topology) GetReplicaOptionsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReplicaOptions, true
}

// SetReplicaOptions sets field value
func (o *Topology) SetReplicaOptions(v string) {
	o.ReplicaOptions = v
}

// GetSysModCount returns the SysModCount field value
func (o *Topology) GetSysModCount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysModCount
}

// GetSysModCountOk returns a tuple with the SysModCount field value
// and a boolean to check if the value has been set.
func (o *Topology) GetSysModCountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysModCount, true
}

// SetSysModCount sets field value
func (o *Topology) SetSysModCount(v string) {
	o.SysModCount = v
}

// GetActive returns the Active field value
func (o *Topology) GetActive() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *Topology) GetActiveOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *Topology) SetActive(v string) {
	o.Active = v
}

// GetSysUpdatedOn returns the SysUpdatedOn field value
func (o *Topology) GetSysUpdatedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysUpdatedOn
}

// GetSysUpdatedOnOk returns a tuple with the SysUpdatedOn field value
// and a boolean to check if the value has been set.
func (o *Topology) GetSysUpdatedOnOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysUpdatedOn, true
}

// SetSysUpdatedOn sets field value
func (o *Topology) SetSysUpdatedOn(v string) {
	o.SysUpdatedOn = v
}

// GetDisplayName returns the DisplayName field value
func (o *Topology) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *Topology) GetDisplayNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *Topology) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetSysTags returns the SysTags field value
func (o *Topology) GetSysTags() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysTags
}

// GetSysTagsOk returns a tuple with the SysTags field value
// and a boolean to check if the value has been set.
func (o *Topology) GetSysTagsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysTags, true
}

// SetSysTags sets field value
func (o *Topology) SetSysTags(v string) {
	o.SysTags = v
}

// GetSysId returns the SysId field value
func (o *Topology) GetSysId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysId
}

// GetSysIdOk returns a tuple with the SysId field value
// and a boolean to check if the value has been set.
func (o *Topology) GetSysIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysId, true
}

// SetSysId sets field value
func (o *Topology) SetSysId(v string) {
	o.SysId = v
}

// GetHasReplicas returns the HasReplicas field value
func (o *Topology) GetHasReplicas() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HasReplicas
}

// GetHasReplicasOk returns a tuple with the HasReplicas field value
// and a boolean to check if the value has been set.
func (o *Topology) GetHasReplicasOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.HasReplicas, true
}

// SetHasReplicas sets field value
func (o *Topology) SetHasReplicas(v string) {
	o.HasReplicas = v
}

// GetSysUpdatedBy returns the SysUpdatedBy field value
func (o *Topology) GetSysUpdatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysUpdatedBy
}

// GetSysUpdatedByOk returns a tuple with the SysUpdatedBy field value
// and a boolean to check if the value has been set.
func (o *Topology) GetSysUpdatedByOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysUpdatedBy, true
}

// SetSysUpdatedBy sets field value
func (o *Topology) SetSysUpdatedBy(v string) {
	o.SysUpdatedBy = v
}

// GetHasClustrixFrontend returns the HasClustrixFrontend field value
func (o *Topology) GetHasClustrixFrontend() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HasClustrixFrontend
}

// GetHasClustrixFrontendOk returns a tuple with the HasClustrixFrontend field value
// and a boolean to check if the value has been set.
func (o *Topology) GetHasClustrixFrontendOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.HasClustrixFrontend, true
}

// SetHasClustrixFrontend sets field value
func (o *Topology) SetHasClustrixFrontend(v string) {
	o.HasClustrixFrontend = v
}

// GetSysCreatedOn returns the SysCreatedOn field value
func (o *Topology) GetSysCreatedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysCreatedOn
}

// GetSysCreatedOnOk returns a tuple with the SysCreatedOn field value
// and a boolean to check if the value has been set.
func (o *Topology) GetSysCreatedOnOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysCreatedOn, true
}

// SetSysCreatedOn sets field value
func (o *Topology) SetSysCreatedOn(v string) {
	o.SysCreatedOn = v
}

// GetName returns the Name field value
func (o *Topology) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Topology) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Topology) SetName(v string) {
	o.Name = v
}

// GetPaid returns the Paid field value
func (o *Topology) GetPaid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Paid
}

// GetPaidOk returns a tuple with the Paid field value
// and a boolean to check if the value has been set.
func (o *Topology) GetPaidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Paid, true
}

// SetPaid sets field value
func (o *Topology) SetPaid(v string) {
	o.Paid = v
}

// GetReplicaLabel returns the ReplicaLabel field value
func (o *Topology) GetReplicaLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReplicaLabel
}

// GetReplicaLabelOk returns a tuple with the ReplicaLabel field value
// and a boolean to check if the value has been set.
func (o *Topology) GetReplicaLabelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReplicaLabel, true
}

// SetReplicaLabel sets field value
func (o *Topology) SetReplicaLabel(v string) {
	o.ReplicaLabel = v
}

// GetMariadbCronbackEnabled returns the MariadbCronbackEnabled field value
func (o *Topology) GetMariadbCronbackEnabled() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MariadbCronbackEnabled
}

// GetMariadbCronbackEnabledOk returns a tuple with the MariadbCronbackEnabled field value
// and a boolean to check if the value has been set.
func (o *Topology) GetMariadbCronbackEnabledOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MariadbCronbackEnabled, true
}

// SetMariadbCronbackEnabled sets field value
func (o *Topology) SetMariadbCronbackEnabled(v string) {
	o.MariadbCronbackEnabled = v
}

// GetValue returns the Value field value
func (o *Topology) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Topology) GetValueOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Topology) SetValue(v string) {
	o.Value = v
}

// GetSysCreatedBy returns the SysCreatedBy field value
func (o *Topology) GetSysCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SysCreatedBy
}

// GetSysCreatedByOk returns a tuple with the SysCreatedBy field value
// and a boolean to check if the value has been set.
func (o *Topology) GetSysCreatedByOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SysCreatedBy, true
}

// SetSysCreatedBy sets field value
func (o *Topology) SetSysCreatedBy(v string) {
	o.SysCreatedBy = v
}

// GetApiHandle returns the ApiHandle field value
func (o *Topology) GetApiHandle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiHandle
}

// GetApiHandleOk returns a tuple with the ApiHandle field value
// and a boolean to check if the value has been set.
func (o *Topology) GetApiHandleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ApiHandle, true
}

// SetApiHandle sets field value
func (o *Topology) SetApiHandle(v string) {
	o.ApiHandle = v
}

func (o Topology) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["maxscale_supported"] = o.MaxscaleSupported
	}
	if true {
		toSerialize["operator_replica_minimum"] = o.OperatorReplicaMinimum
	}
	if true {
		toSerialize["product"] = o.Product
	}
	if true {
		toSerialize["replica_options"] = o.ReplicaOptions
	}
	if true {
		toSerialize["sys_mod_count"] = o.SysModCount
	}
	if true {
		toSerialize["active"] = o.Active
	}
	if true {
		toSerialize["sys_updated_on"] = o.SysUpdatedOn
	}
	if true {
		toSerialize["display_name"] = o.DisplayName
	}
	if true {
		toSerialize["sys_tags"] = o.SysTags
	}
	if true {
		toSerialize["sys_id"] = o.SysId
	}
	if true {
		toSerialize["has_replicas"] = o.HasReplicas
	}
	if true {
		toSerialize["sys_updated_by"] = o.SysUpdatedBy
	}
	if true {
		toSerialize["has_clustrix_frontend"] = o.HasClustrixFrontend
	}
	if true {
		toSerialize["sys_created_on"] = o.SysCreatedOn
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["paid"] = o.Paid
	}
	if true {
		toSerialize["replica_label"] = o.ReplicaLabel
	}
	if true {
		toSerialize["mariadb_cronback_enabled"] = o.MariadbCronbackEnabled
	}
	if true {
		toSerialize["value"] = o.Value
	}
	if true {
		toSerialize["sys_created_by"] = o.SysCreatedBy
	}
	if true {
		toSerialize["api_handle"] = o.ApiHandle
	}
	return json.Marshal(toSerialize)
}

type NullableTopology struct {
	value *Topology
	isSet bool
}

func (v NullableTopology) Get() *Topology {
	return v.value
}

func (v *NullableTopology) Set(val *Topology) {
	v.value = val
	v.isSet = true
}

func (v NullableTopology) IsSet() bool {
	return v.isSet
}

func (v *NullableTopology) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopology(val *Topology) *NullableTopology {
	return &NullableTopology{value: val, isSet: true}
}

func (v NullableTopology) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopology) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


