// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateServiceRequest v1 create service request
//
// swagger:model v1.CreateServiceRequest
type V1CreateServiceRequest struct {

	// name
	// Example: doc-test-tx-single
	Name string `json:"name,omitempty"`

	// nodes
	// Example: 1
	Nodes int64 `json:"nodes,omitempty"`

	// project id
	// Example: b4ffd36d-20b2-4813-9939-635f66a21c5e
	ProjectID string `json:"project_id,omitempty"`

	// provider
	// Example: aws
	Provider string `json:"provider,omitempty"`

	// region
	// Example: us-east-1
	Region string `json:"region,omitempty"`

	// service type
	// Example: transactional
	ServiceType string `json:"service_type,omitempty"`

	// size
	// Example: sky-2x8
	Size string `json:"size,omitempty"`

	// ssl enabled
	// Example: true
	SslEnabled bool `json:"ssl_enabled,omitempty"`

	// storage
	// Example: 100
	Storage int64 `json:"storage,omitempty"`

	// tier
	// Example: foundation
	Tier string `json:"tier,omitempty"`

	// topology
	// Example: standalone
	Topology string `json:"topology,omitempty"`

	// version
	// Example: 10.6.7-3-1
	Version string `json:"version,omitempty"`

	// volume iops
	// Example: 100
	VolumeIops int64 `json:"volume_iops,omitempty"`

	// volume type
	// Example: gp2
	VolumeType string `json:"volume_type,omitempty"`
}

// Validate validates this v1 create service request
func (m *V1CreateServiceRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 create service request based on context it is used
func (m *V1CreateServiceRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateServiceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateServiceRequest) UnmarshalBinary(b []byte) error {
	var res V1CreateServiceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
