// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1DeleteAllowedAddressRequest v1 delete allowed address request
//
// swagger:model v1.DeleteAllowedAddressRequest
type V1DeleteAllowedAddressRequest struct {

	// ip address
	// Example: 142.251.46.142/32
	IPAddress string `json:"ip_address,omitempty"`
}

// Validate validates this v1 delete allowed address request
func (m *V1DeleteAllowedAddressRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 delete allowed address request based on context it is used
func (m *V1DeleteAllowedAddressRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1DeleteAllowedAddressRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1DeleteAllowedAddressRequest) UnmarshalBinary(b []byte) error {
	var res V1DeleteAllowedAddressRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
