// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1PatchAccountRequest v1 patch account request
//
// swagger:model v1.PatchAccountRequest
type V1PatchAccountRequest struct {

	// account id
	AccountID string `json:"account_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// tier
	Tier string `json:"tier,omitempty"`
}

// Validate validates this v1 patch account request
func (m *V1PatchAccountRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 patch account request based on context it is used
func (m *V1PatchAccountRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1PatchAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1PatchAccountRequest) UnmarshalBinary(b []byte) error {
	var res V1PatchAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
