// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Region Geographic region, as defined by the provider
//
// swagger:model v1.Region
type V1Region struct {

	// default
	Default bool `json:"default,omitempty"`

	// has clusters
	HasClusters bool `json:"has_clusters,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// region
	Region string `json:"region,omitempty"`
}

// Validate validates this v1 region
func (m *V1Region) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 region based on context it is used
func (m *V1Region) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Region) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Region) UnmarshalBinary(b []byte) error {
	var res V1Region
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
