// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SetStorageSizeRequest Storage size that is set for the service
//
// swagger:model v1.SetStorageSizeRequest
type V1SetStorageSizeRequest struct {

	// Size in GBs
	// Example: 10
	Size int64 `json:"size,omitempty"`
}

// Validate validates this v1 set storage size request
func (m *V1SetStorageSizeRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 set storage size request based on context it is used
func (m *V1SetStorageSizeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SetStorageSizeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SetStorageSizeRequest) UnmarshalBinary(b []byte) error {
	var res V1SetStorageSizeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
