// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// GetProvisioningV1ServicesServiceIDReader is a Reader for the GetProvisioningV1ServicesServiceID structure.
type GetProvisioningV1ServicesServiceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvisioningV1ServicesServiceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProvisioningV1ServicesServiceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProvisioningV1ServicesServiceIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProvisioningV1ServicesServiceIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProvisioningV1ServicesServiceIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProvisioningV1ServicesServiceIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProvisioningV1ServicesServiceIDOK creates a GetProvisioningV1ServicesServiceIDOK with default headers values
func NewGetProvisioningV1ServicesServiceIDOK() *GetProvisioningV1ServicesServiceIDOK {
	return &GetProvisioningV1ServicesServiceIDOK{}
}

/* GetProvisioningV1ServicesServiceIDOK describes a response with status code 200, with default header values.

OK
*/
type GetProvisioningV1ServicesServiceIDOK struct {
	Payload *models.V1ServiceResponse
}

func (o *GetProvisioningV1ServicesServiceIDOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}][%d] getProvisioningV1ServicesServiceIdOK  %+v", 200, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDOK) GetPayload() *models.V1ServiceResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ServiceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ServicesServiceIDBadRequest creates a GetProvisioningV1ServicesServiceIDBadRequest with default headers values
func NewGetProvisioningV1ServicesServiceIDBadRequest() *GetProvisioningV1ServicesServiceIDBadRequest {
	return &GetProvisioningV1ServicesServiceIDBadRequest{}
}

/* GetProvisioningV1ServicesServiceIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProvisioningV1ServicesServiceIDBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ServicesServiceIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}][%d] getProvisioningV1ServicesServiceIdBadRequest  %+v", 400, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ServicesServiceIDUnauthorized creates a GetProvisioningV1ServicesServiceIDUnauthorized with default headers values
func NewGetProvisioningV1ServicesServiceIDUnauthorized() *GetProvisioningV1ServicesServiceIDUnauthorized {
	return &GetProvisioningV1ServicesServiceIDUnauthorized{}
}

/* GetProvisioningV1ServicesServiceIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProvisioningV1ServicesServiceIDUnauthorized struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ServicesServiceIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}][%d] getProvisioningV1ServicesServiceIdUnauthorized  %+v", 401, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDUnauthorized) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ServicesServiceIDNotFound creates a GetProvisioningV1ServicesServiceIDNotFound with default headers values
func NewGetProvisioningV1ServicesServiceIDNotFound() *GetProvisioningV1ServicesServiceIDNotFound {
	return &GetProvisioningV1ServicesServiceIDNotFound{}
}

/* GetProvisioningV1ServicesServiceIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetProvisioningV1ServicesServiceIDNotFound struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ServicesServiceIDNotFound) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}][%d] getProvisioningV1ServicesServiceIdNotFound  %+v", 404, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDNotFound) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ServicesServiceIDInternalServerError creates a GetProvisioningV1ServicesServiceIDInternalServerError with default headers values
func NewGetProvisioningV1ServicesServiceIDInternalServerError() *GetProvisioningV1ServicesServiceIDInternalServerError {
	return &GetProvisioningV1ServicesServiceIDInternalServerError{}
}

/* GetProvisioningV1ServicesServiceIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProvisioningV1ServicesServiceIDInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ServicesServiceIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}][%d] getProvisioningV1ServicesServiceIdInternalServerError  %+v", 500, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
