// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// NewPatchProvisioningV1InternalServicesServiceIDParams creates a new PatchProvisioningV1InternalServicesServiceIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchProvisioningV1InternalServicesServiceIDParams() *PatchProvisioningV1InternalServicesServiceIDParams {
	return &PatchProvisioningV1InternalServicesServiceIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchProvisioningV1InternalServicesServiceIDParamsWithTimeout creates a new PatchProvisioningV1InternalServicesServiceIDParams object
// with the ability to set a timeout on a request.
func NewPatchProvisioningV1InternalServicesServiceIDParamsWithTimeout(timeout time.Duration) *PatchProvisioningV1InternalServicesServiceIDParams {
	return &PatchProvisioningV1InternalServicesServiceIDParams{
		timeout: timeout,
	}
}

// NewPatchProvisioningV1InternalServicesServiceIDParamsWithContext creates a new PatchProvisioningV1InternalServicesServiceIDParams object
// with the ability to set a context for a request.
func NewPatchProvisioningV1InternalServicesServiceIDParamsWithContext(ctx context.Context) *PatchProvisioningV1InternalServicesServiceIDParams {
	return &PatchProvisioningV1InternalServicesServiceIDParams{
		Context: ctx,
	}
}

// NewPatchProvisioningV1InternalServicesServiceIDParamsWithHTTPClient creates a new PatchProvisioningV1InternalServicesServiceIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchProvisioningV1InternalServicesServiceIDParamsWithHTTPClient(client *http.Client) *PatchProvisioningV1InternalServicesServiceIDParams {
	return &PatchProvisioningV1InternalServicesServiceIDParams{
		HTTPClient: client,
	}
}

/* PatchProvisioningV1InternalServicesServiceIDParams contains all the parameters to send to the API endpoint
   for the patch provisioning v1 internal services service ID operation.

   Typically these are written to a http.Request.
*/
type PatchProvisioningV1InternalServicesServiceIDParams struct {

	/* Request.

	   Request Body
	*/
	Request *models.V1PatchServiceRequest

	/* ServiceID.

	   Identifier for a services
	*/
	ServiceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch provisioning v1 internal services service ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchProvisioningV1InternalServicesServiceIDParams) WithDefaults() *PatchProvisioningV1InternalServicesServiceIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch provisioning v1 internal services service ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchProvisioningV1InternalServicesServiceIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) WithTimeout(timeout time.Duration) *PatchProvisioningV1InternalServicesServiceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) WithContext(ctx context.Context) *PatchProvisioningV1InternalServicesServiceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) WithHTTPClient(client *http.Client) *PatchProvisioningV1InternalServicesServiceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) WithRequest(request *models.V1PatchServiceRequest) *PatchProvisioningV1InternalServicesServiceIDParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) SetRequest(request *models.V1PatchServiceRequest) {
	o.Request = request
}

// WithServiceID adds the serviceID to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) WithServiceID(serviceID string) *PatchProvisioningV1InternalServicesServiceIDParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the patch provisioning v1 internal services service ID params
func (o *PatchProvisioningV1InternalServicesServiceIDParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchProvisioningV1InternalServicesServiceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param service_id
	if err := r.SetPathParam("service_id", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
