// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// NewPostProvisioningV1ServicesParams creates a new PostProvisioningV1ServicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProvisioningV1ServicesParams() *PostProvisioningV1ServicesParams {
	return &PostProvisioningV1ServicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProvisioningV1ServicesParamsWithTimeout creates a new PostProvisioningV1ServicesParams object
// with the ability to set a timeout on a request.
func NewPostProvisioningV1ServicesParamsWithTimeout(timeout time.Duration) *PostProvisioningV1ServicesParams {
	return &PostProvisioningV1ServicesParams{
		timeout: timeout,
	}
}

// NewPostProvisioningV1ServicesParamsWithContext creates a new PostProvisioningV1ServicesParams object
// with the ability to set a context for a request.
func NewPostProvisioningV1ServicesParamsWithContext(ctx context.Context) *PostProvisioningV1ServicesParams {
	return &PostProvisioningV1ServicesParams{
		Context: ctx,
	}
}

// NewPostProvisioningV1ServicesParamsWithHTTPClient creates a new PostProvisioningV1ServicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProvisioningV1ServicesParamsWithHTTPClient(client *http.Client) *PostProvisioningV1ServicesParams {
	return &PostProvisioningV1ServicesParams{
		HTTPClient: client,
	}
}

/* PostProvisioningV1ServicesParams contains all the parameters to send to the API endpoint
   for the post provisioning v1 services operation.

   Typically these are written to a http.Request.
*/
type PostProvisioningV1ServicesParams struct {

	/* Request.

	   Request Body
	*/
	Request *models.V1CreateServiceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post provisioning v1 services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProvisioningV1ServicesParams) WithDefaults() *PostProvisioningV1ServicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post provisioning v1 services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProvisioningV1ServicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post provisioning v1 services params
func (o *PostProvisioningV1ServicesParams) WithTimeout(timeout time.Duration) *PostProvisioningV1ServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post provisioning v1 services params
func (o *PostProvisioningV1ServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post provisioning v1 services params
func (o *PostProvisioningV1ServicesParams) WithContext(ctx context.Context) *PostProvisioningV1ServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post provisioning v1 services params
func (o *PostProvisioningV1ServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post provisioning v1 services params
func (o *PostProvisioningV1ServicesParams) WithHTTPClient(client *http.Client) *PostProvisioningV1ServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post provisioning v1 services params
func (o *PostProvisioningV1ServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post provisioning v1 services params
func (o *PostProvisioningV1ServicesParams) WithRequest(request *models.V1CreateServiceRequest) *PostProvisioningV1ServicesParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post provisioning v1 services params
func (o *PostProvisioningV1ServicesParams) SetRequest(request *models.V1CreateServiceRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostProvisioningV1ServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
