// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// NewPostProvisioningV1ServicesServiceIDStorageIopsParams creates a new PostProvisioningV1ServicesServiceIDStorageIopsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProvisioningV1ServicesServiceIDStorageIopsParams() *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	return &PostProvisioningV1ServicesServiceIDStorageIopsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProvisioningV1ServicesServiceIDStorageIopsParamsWithTimeout creates a new PostProvisioningV1ServicesServiceIDStorageIopsParams object
// with the ability to set a timeout on a request.
func NewPostProvisioningV1ServicesServiceIDStorageIopsParamsWithTimeout(timeout time.Duration) *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	return &PostProvisioningV1ServicesServiceIDStorageIopsParams{
		timeout: timeout,
	}
}

// NewPostProvisioningV1ServicesServiceIDStorageIopsParamsWithContext creates a new PostProvisioningV1ServicesServiceIDStorageIopsParams object
// with the ability to set a context for a request.
func NewPostProvisioningV1ServicesServiceIDStorageIopsParamsWithContext(ctx context.Context) *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	return &PostProvisioningV1ServicesServiceIDStorageIopsParams{
		Context: ctx,
	}
}

// NewPostProvisioningV1ServicesServiceIDStorageIopsParamsWithHTTPClient creates a new PostProvisioningV1ServicesServiceIDStorageIopsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProvisioningV1ServicesServiceIDStorageIopsParamsWithHTTPClient(client *http.Client) *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	return &PostProvisioningV1ServicesServiceIDStorageIopsParams{
		HTTPClient: client,
	}
}

/* PostProvisioningV1ServicesServiceIDStorageIopsParams contains all the parameters to send to the API endpoint
   for the post provisioning v1 services service ID storage iops operation.

   Typically these are written to a http.Request.
*/
type PostProvisioningV1ServicesServiceIDStorageIopsParams struct {

	/* Request.

	   Request Body
	*/
	Request *models.V1SetStorageIOPSRequest

	/* ServiceID.

	   Identifier for a services
	*/
	ServiceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post provisioning v1 services service ID storage iops params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) WithDefaults() *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post provisioning v1 services service ID storage iops params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) WithTimeout(timeout time.Duration) *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) WithContext(ctx context.Context) *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) WithHTTPClient(client *http.Client) *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) WithRequest(request *models.V1SetStorageIOPSRequest) *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) SetRequest(request *models.V1SetStorageIOPSRequest) {
	o.Request = request
}

// WithServiceID adds the serviceID to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) WithServiceID(serviceID string) *PostProvisioningV1ServicesServiceIDStorageIopsParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the post provisioning v1 services service ID storage iops params
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *PostProvisioningV1ServicesServiceIDStorageIopsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param service_id
	if err := r.SetPathParam("service_id", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
