// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// PatchProvisioningV1InternalClusterClusterIDReader is a Reader for the PatchProvisioningV1InternalClusterClusterID structure.
type PatchProvisioningV1InternalClusterClusterIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchProvisioningV1InternalClusterClusterIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPatchProvisioningV1InternalClusterClusterIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchProvisioningV1InternalClusterClusterIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPatchProvisioningV1InternalClusterClusterIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPatchProvisioningV1InternalClusterClusterIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchProvisioningV1InternalClusterClusterIDNoContent creates a PatchProvisioningV1InternalClusterClusterIDNoContent with default headers values
func NewPatchProvisioningV1InternalClusterClusterIDNoContent() *PatchProvisioningV1InternalClusterClusterIDNoContent {
	return &PatchProvisioningV1InternalClusterClusterIDNoContent{}
}

/* PatchProvisioningV1InternalClusterClusterIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type PatchProvisioningV1InternalClusterClusterIDNoContent struct {
}

func (o *PatchProvisioningV1InternalClusterClusterIDNoContent) Error() string {
	return fmt.Sprintf("[PATCH /provisioning/v1/internal/cluster/{cluster_id}][%d] patchProvisioningV1InternalClusterClusterIdNoContent ", 204)
}

func (o *PatchProvisioningV1InternalClusterClusterIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchProvisioningV1InternalClusterClusterIDBadRequest creates a PatchProvisioningV1InternalClusterClusterIDBadRequest with default headers values
func NewPatchProvisioningV1InternalClusterClusterIDBadRequest() *PatchProvisioningV1InternalClusterClusterIDBadRequest {
	return &PatchProvisioningV1InternalClusterClusterIDBadRequest{}
}

/* PatchProvisioningV1InternalClusterClusterIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PatchProvisioningV1InternalClusterClusterIDBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *PatchProvisioningV1InternalClusterClusterIDBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /provisioning/v1/internal/cluster/{cluster_id}][%d] patchProvisioningV1InternalClusterClusterIdBadRequest  %+v", 400, o.Payload)
}
func (o *PatchProvisioningV1InternalClusterClusterIDBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *PatchProvisioningV1InternalClusterClusterIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchProvisioningV1InternalClusterClusterIDNotFound creates a PatchProvisioningV1InternalClusterClusterIDNotFound with default headers values
func NewPatchProvisioningV1InternalClusterClusterIDNotFound() *PatchProvisioningV1InternalClusterClusterIDNotFound {
	return &PatchProvisioningV1InternalClusterClusterIDNotFound{}
}

/* PatchProvisioningV1InternalClusterClusterIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PatchProvisioningV1InternalClusterClusterIDNotFound struct {
	Payload *models.ErrrErrorResponse
}

func (o *PatchProvisioningV1InternalClusterClusterIDNotFound) Error() string {
	return fmt.Sprintf("[PATCH /provisioning/v1/internal/cluster/{cluster_id}][%d] patchProvisioningV1InternalClusterClusterIdNotFound  %+v", 404, o.Payload)
}
func (o *PatchProvisioningV1InternalClusterClusterIDNotFound) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *PatchProvisioningV1InternalClusterClusterIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchProvisioningV1InternalClusterClusterIDInternalServerError creates a PatchProvisioningV1InternalClusterClusterIDInternalServerError with default headers values
func NewPatchProvisioningV1InternalClusterClusterIDInternalServerError() *PatchProvisioningV1InternalClusterClusterIDInternalServerError {
	return &PatchProvisioningV1InternalClusterClusterIDInternalServerError{}
}

/* PatchProvisioningV1InternalClusterClusterIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PatchProvisioningV1InternalClusterClusterIDInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *PatchProvisioningV1InternalClusterClusterIDInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /provisioning/v1/internal/cluster/{cluster_id}][%d] patchProvisioningV1InternalClusterClusterIdInternalServerError  %+v", 500, o.Payload)
}
func (o *PatchProvisioningV1InternalClusterClusterIDInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *PatchProvisioningV1InternalClusterClusterIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
