// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// NewPatchProvisioningV1InternalClusterClusterIDParams creates a new PatchProvisioningV1InternalClusterClusterIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchProvisioningV1InternalClusterClusterIDParams() *PatchProvisioningV1InternalClusterClusterIDParams {
	return &PatchProvisioningV1InternalClusterClusterIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchProvisioningV1InternalClusterClusterIDParamsWithTimeout creates a new PatchProvisioningV1InternalClusterClusterIDParams object
// with the ability to set a timeout on a request.
func NewPatchProvisioningV1InternalClusterClusterIDParamsWithTimeout(timeout time.Duration) *PatchProvisioningV1InternalClusterClusterIDParams {
	return &PatchProvisioningV1InternalClusterClusterIDParams{
		timeout: timeout,
	}
}

// NewPatchProvisioningV1InternalClusterClusterIDParamsWithContext creates a new PatchProvisioningV1InternalClusterClusterIDParams object
// with the ability to set a context for a request.
func NewPatchProvisioningV1InternalClusterClusterIDParamsWithContext(ctx context.Context) *PatchProvisioningV1InternalClusterClusterIDParams {
	return &PatchProvisioningV1InternalClusterClusterIDParams{
		Context: ctx,
	}
}

// NewPatchProvisioningV1InternalClusterClusterIDParamsWithHTTPClient creates a new PatchProvisioningV1InternalClusterClusterIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchProvisioningV1InternalClusterClusterIDParamsWithHTTPClient(client *http.Client) *PatchProvisioningV1InternalClusterClusterIDParams {
	return &PatchProvisioningV1InternalClusterClusterIDParams{
		HTTPClient: client,
	}
}

/* PatchProvisioningV1InternalClusterClusterIDParams contains all the parameters to send to the API endpoint
   for the patch provisioning v1 internal cluster cluster ID operation.

   Typically these are written to a http.Request.
*/
type PatchProvisioningV1InternalClusterClusterIDParams struct {

	/* ClusterID.

	   Identifier for a services
	*/
	ClusterID string

	/* Request.

	   Request Body
	*/
	Request *models.V1PatchClusterRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch provisioning v1 internal cluster cluster ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchProvisioningV1InternalClusterClusterIDParams) WithDefaults() *PatchProvisioningV1InternalClusterClusterIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch provisioning v1 internal cluster cluster ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchProvisioningV1InternalClusterClusterIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) WithTimeout(timeout time.Duration) *PatchProvisioningV1InternalClusterClusterIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) WithContext(ctx context.Context) *PatchProvisioningV1InternalClusterClusterIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) WithHTTPClient(client *http.Client) *PatchProvisioningV1InternalClusterClusterIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) WithClusterID(clusterID string) *PatchProvisioningV1InternalClusterClusterIDParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithRequest adds the request to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) WithRequest(request *models.V1PatchClusterRequest) *PatchProvisioningV1InternalClusterClusterIDParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the patch provisioning v1 internal cluster cluster ID params
func (o *PatchProvisioningV1InternalClusterClusterIDParams) SetRequest(request *models.V1PatchClusterRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PatchProvisioningV1InternalClusterClusterIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
