// Code generated by go-swagger; DO NOT EDIT.

package get_subscribers_channel_email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams creates a new GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams() *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	return &GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithTimeout creates a new GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams object
// with the ability to set a timeout on a request.
func NewGetNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithTimeout(timeout time.Duration) *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	return &GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams{
		timeout: timeout,
	}
}

// NewGetNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithContext creates a new GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams object
// with the ability to set a context for a request.
func NewGetNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithContext(ctx context.Context) *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	return &GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams{
		Context: ctx,
	}
}

// NewGetNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithHTTPClient creates a new GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithHTTPClient(client *http.Client) *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	return &GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams{
		HTTPClient: client,
	}
}

/* GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams contains all the parameters to send to the API endpoint
   for the get notifications v1 subscribers subscriber ID channels emails operation.

   Typically these are written to a http.Request.
*/
type GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams struct {

	/* SubscriberID.

	   subscriber id i.e. user id
	*/
	SubscriberID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get notifications v1 subscribers subscriber ID channels emails params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithDefaults() *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get notifications v1 subscribers subscriber ID channels emails params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get notifications v1 subscribers subscriber ID channels emails params
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithTimeout(timeout time.Duration) *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get notifications v1 subscribers subscriber ID channels emails params
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get notifications v1 subscribers subscriber ID channels emails params
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithContext(ctx context.Context) *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get notifications v1 subscribers subscriber ID channels emails params
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get notifications v1 subscribers subscriber ID channels emails params
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithHTTPClient(client *http.Client) *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get notifications v1 subscribers subscriber ID channels emails params
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubscriberID adds the subscriberID to the get notifications v1 subscribers subscriber ID channels emails params
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithSubscriberID(subscriberID string) *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetSubscriberID(subscriberID)
	return o
}

// SetSubscriberID adds the subscriberId to the get notifications v1 subscribers subscriber ID channels emails params
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetSubscriberID(subscriberID string) {
	o.SubscriberID = subscriberID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subscriber_id
	if err := r.SetPathParam("subscriber_id", o.SubscriberID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
