// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// GetProvisioningV1ProductsReader is a Reader for the GetProvisioningV1Products structure.
type GetProvisioningV1ProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvisioningV1ProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProvisioningV1ProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProvisioningV1ProductsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProvisioningV1ProductsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProvisioningV1ProductsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProvisioningV1ProductsOK creates a GetProvisioningV1ProductsOK with default headers values
func NewGetProvisioningV1ProductsOK() *GetProvisioningV1ProductsOK {
	return &GetProvisioningV1ProductsOK{}
}

/* GetProvisioningV1ProductsOK describes a response with status code 200, with default header values.

OK
*/
type GetProvisioningV1ProductsOK struct {
	Payload []*models.V1Product
}

func (o *GetProvisioningV1ProductsOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/products][%d] getProvisioningV1ProductsOK  %+v", 200, o.Payload)
}
func (o *GetProvisioningV1ProductsOK) GetPayload() []*models.V1Product {
	return o.Payload
}

func (o *GetProvisioningV1ProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProductsBadRequest creates a GetProvisioningV1ProductsBadRequest with default headers values
func NewGetProvisioningV1ProductsBadRequest() *GetProvisioningV1ProductsBadRequest {
	return &GetProvisioningV1ProductsBadRequest{}
}

/* GetProvisioningV1ProductsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProvisioningV1ProductsBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProductsBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/products][%d] getProvisioningV1ProductsBadRequest  %+v", 400, o.Payload)
}
func (o *GetProvisioningV1ProductsBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProductsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProductsUnauthorized creates a GetProvisioningV1ProductsUnauthorized with default headers values
func NewGetProvisioningV1ProductsUnauthorized() *GetProvisioningV1ProductsUnauthorized {
	return &GetProvisioningV1ProductsUnauthorized{}
}

/* GetProvisioningV1ProductsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProvisioningV1ProductsUnauthorized struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProductsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/products][%d] getProvisioningV1ProductsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetProvisioningV1ProductsUnauthorized) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProductsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProductsInternalServerError creates a GetProvisioningV1ProductsInternalServerError with default headers values
func NewGetProvisioningV1ProductsInternalServerError() *GetProvisioningV1ProductsInternalServerError {
	return &GetProvisioningV1ProductsInternalServerError{}
}

/* GetProvisioningV1ProductsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProvisioningV1ProductsInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProductsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/products][%d] getProvisioningV1ProductsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetProvisioningV1ProductsInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProductsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
