// Code generated by go-swagger; DO NOT EDIT.

package delete_preference

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/nos/models"
)

// DeleteNotificationsV1PreferencesPreferenceIDReader is a Reader for the DeleteNotificationsV1PreferencesPreferenceID structure.
type DeleteNotificationsV1PreferencesPreferenceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNotificationsV1PreferencesPreferenceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteNotificationsV1PreferencesPreferenceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteNotificationsV1PreferencesPreferenceIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteNotificationsV1PreferencesPreferenceIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteNotificationsV1PreferencesPreferenceIDOK creates a DeleteNotificationsV1PreferencesPreferenceIDOK with default headers values
func NewDeleteNotificationsV1PreferencesPreferenceIDOK() *DeleteNotificationsV1PreferencesPreferenceIDOK {
	return &DeleteNotificationsV1PreferencesPreferenceIDOK{}
}

/* DeleteNotificationsV1PreferencesPreferenceIDOK describes a response with status code 200, with default header values.

DeleteNotificationsV1PreferencesPreferenceIDOK delete notifications v1 preferences preference Id o k
*/
type DeleteNotificationsV1PreferencesPreferenceIDOK struct {
}

func (o *DeleteNotificationsV1PreferencesPreferenceIDOK) Error() string {
	return fmt.Sprintf("[DELETE /notifications/v1/preferences/{preference_id}][%d] deleteNotificationsV1PreferencesPreferenceIdOK ", 200)
}

func (o *DeleteNotificationsV1PreferencesPreferenceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNotificationsV1PreferencesPreferenceIDUnauthorized creates a DeleteNotificationsV1PreferencesPreferenceIDUnauthorized with default headers values
func NewDeleteNotificationsV1PreferencesPreferenceIDUnauthorized() *DeleteNotificationsV1PreferencesPreferenceIDUnauthorized {
	return &DeleteNotificationsV1PreferencesPreferenceIDUnauthorized{}
}

/* DeleteNotificationsV1PreferencesPreferenceIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteNotificationsV1PreferencesPreferenceIDUnauthorized struct {
	Payload *models.ErrrErrorResponse
}

func (o *DeleteNotificationsV1PreferencesPreferenceIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /notifications/v1/preferences/{preference_id}][%d] deleteNotificationsV1PreferencesPreferenceIdUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteNotificationsV1PreferencesPreferenceIDUnauthorized) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *DeleteNotificationsV1PreferencesPreferenceIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNotificationsV1PreferencesPreferenceIDNotFound creates a DeleteNotificationsV1PreferencesPreferenceIDNotFound with default headers values
func NewDeleteNotificationsV1PreferencesPreferenceIDNotFound() *DeleteNotificationsV1PreferencesPreferenceIDNotFound {
	return &DeleteNotificationsV1PreferencesPreferenceIDNotFound{}
}

/* DeleteNotificationsV1PreferencesPreferenceIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteNotificationsV1PreferencesPreferenceIDNotFound struct {
	Payload *models.ErrrErrorResponse
}

func (o *DeleteNotificationsV1PreferencesPreferenceIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /notifications/v1/preferences/{preference_id}][%d] deleteNotificationsV1PreferencesPreferenceIdNotFound  %+v", 404, o.Payload)
}
func (o *DeleteNotificationsV1PreferencesPreferenceIDNotFound) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *DeleteNotificationsV1PreferencesPreferenceIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
