// Code generated by go-swagger; DO NOT EDIT.

package offering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// GetProvisioningV1TiersReader is a Reader for the GetProvisioningV1Tiers structure.
type GetProvisioningV1TiersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvisioningV1TiersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProvisioningV1TiersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProvisioningV1TiersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProvisioningV1TiersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProvisioningV1TiersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProvisioningV1TiersOK creates a GetProvisioningV1TiersOK with default headers values
func NewGetProvisioningV1TiersOK() *GetProvisioningV1TiersOK {
	return &GetProvisioningV1TiersOK{}
}

/* GetProvisioningV1TiersOK describes a response with status code 200, with default header values.

OK
*/
type GetProvisioningV1TiersOK struct {
	Payload []*models.V1Tier
}

func (o *GetProvisioningV1TiersOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/tiers][%d] getProvisioningV1TiersOK  %+v", 200, o.Payload)
}
func (o *GetProvisioningV1TiersOK) GetPayload() []*models.V1Tier {
	return o.Payload
}

func (o *GetProvisioningV1TiersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1TiersBadRequest creates a GetProvisioningV1TiersBadRequest with default headers values
func NewGetProvisioningV1TiersBadRequest() *GetProvisioningV1TiersBadRequest {
	return &GetProvisioningV1TiersBadRequest{}
}

/* GetProvisioningV1TiersBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProvisioningV1TiersBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1TiersBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/tiers][%d] getProvisioningV1TiersBadRequest  %+v", 400, o.Payload)
}
func (o *GetProvisioningV1TiersBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1TiersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1TiersUnauthorized creates a GetProvisioningV1TiersUnauthorized with default headers values
func NewGetProvisioningV1TiersUnauthorized() *GetProvisioningV1TiersUnauthorized {
	return &GetProvisioningV1TiersUnauthorized{}
}

/* GetProvisioningV1TiersUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProvisioningV1TiersUnauthorized struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1TiersUnauthorized) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/tiers][%d] getProvisioningV1TiersUnauthorized  %+v", 401, o.Payload)
}
func (o *GetProvisioningV1TiersUnauthorized) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1TiersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1TiersInternalServerError creates a GetProvisioningV1TiersInternalServerError with default headers values
func NewGetProvisioningV1TiersInternalServerError() *GetProvisioningV1TiersInternalServerError {
	return &GetProvisioningV1TiersInternalServerError{}
}

/* GetProvisioningV1TiersInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProvisioningV1TiersInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1TiersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/tiers][%d] getProvisioningV1TiersInternalServerError  %+v", 500, o.Payload)
}
func (o *GetProvisioningV1TiersInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1TiersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
