// Code generated by go-swagger; DO NOT EDIT.

package offering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// GetProvisioningV1ProvidersProviderNameVolumeTypesReader is a Reader for the GetProvisioningV1ProvidersProviderNameVolumeTypes structure.
type GetProvisioningV1ProvidersProviderNameVolumeTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProvisioningV1ProvidersProviderNameVolumeTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProvisioningV1ProvidersProviderNameVolumeTypesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProvisioningV1ProvidersProviderNameVolumeTypesOK creates a GetProvisioningV1ProvidersProviderNameVolumeTypesOK with default headers values
func NewGetProvisioningV1ProvidersProviderNameVolumeTypesOK() *GetProvisioningV1ProvidersProviderNameVolumeTypesOK {
	return &GetProvisioningV1ProvidersProviderNameVolumeTypesOK{}
}

/* GetProvisioningV1ProvidersProviderNameVolumeTypesOK describes a response with status code 200, with default header values.

OK
*/
type GetProvisioningV1ProvidersProviderNameVolumeTypesOK struct {
	Payload []*models.V1VolumeTypeResponse
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/providers/{provider_name}/volume-types][%d] getProvisioningV1ProvidersProviderNameVolumeTypesOK  %+v", 200, o.Payload)
}
func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesOK) GetPayload() []*models.V1VolumeTypeResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest creates a GetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest with default headers values
func NewGetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest() *GetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest {
	return &GetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest{}
}

/* GetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/providers/{provider_name}/volume-types][%d] getProvisioningV1ProvidersProviderNameVolumeTypesBadRequest  %+v", 400, o.Payload)
}
func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized creates a GetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized with default headers values
func NewGetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized() *GetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized {
	return &GetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized{}
}

/* GetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/providers/{provider_name}/volume-types][%d] getProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized  %+v", 401, o.Payload)
}
func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProvidersProviderNameVolumeTypesNotFound creates a GetProvisioningV1ProvidersProviderNameVolumeTypesNotFound with default headers values
func NewGetProvisioningV1ProvidersProviderNameVolumeTypesNotFound() *GetProvisioningV1ProvidersProviderNameVolumeTypesNotFound {
	return &GetProvisioningV1ProvidersProviderNameVolumeTypesNotFound{}
}

/* GetProvisioningV1ProvidersProviderNameVolumeTypesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetProvisioningV1ProvidersProviderNameVolumeTypesNotFound struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesNotFound) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/providers/{provider_name}/volume-types][%d] getProvisioningV1ProvidersProviderNameVolumeTypesNotFound  %+v", 404, o.Payload)
}
func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesNotFound) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError creates a GetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError with default headers values
func NewGetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError() *GetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError {
	return &GetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError{}
}

/* GetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/providers/{provider_name}/volume-types][%d] getProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError  %+v", 500, o.Payload)
}
func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProvidersProviderNameVolumeTypesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
