// Code generated by go-swagger; DO NOT EDIT.

package offering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProvisioningV1TiersParams creates a new GetProvisioningV1TiersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProvisioningV1TiersParams() *GetProvisioningV1TiersParams {
	return &GetProvisioningV1TiersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProvisioningV1TiersParamsWithTimeout creates a new GetProvisioningV1TiersParams object
// with the ability to set a timeout on a request.
func NewGetProvisioningV1TiersParamsWithTimeout(timeout time.Duration) *GetProvisioningV1TiersParams {
	return &GetProvisioningV1TiersParams{
		timeout: timeout,
	}
}

// NewGetProvisioningV1TiersParamsWithContext creates a new GetProvisioningV1TiersParams object
// with the ability to set a context for a request.
func NewGetProvisioningV1TiersParamsWithContext(ctx context.Context) *GetProvisioningV1TiersParams {
	return &GetProvisioningV1TiersParams{
		Context: ctx,
	}
}

// NewGetProvisioningV1TiersParamsWithHTTPClient creates a new GetProvisioningV1TiersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProvisioningV1TiersParamsWithHTTPClient(client *http.Client) *GetProvisioningV1TiersParams {
	return &GetProvisioningV1TiersParams{
		HTTPClient: client,
	}
}

/* GetProvisioningV1TiersParams contains all the parameters to send to the API endpoint
   for the get provisioning v1 tiers operation.

   Typically these are written to a http.Request.
*/
type GetProvisioningV1TiersParams struct {

	/* PageOrder.

	   page_order
	*/
	PageOrder *string

	/* PageSize.

	   page_size

	   Default: 10
	*/
	PageSize *int64

	/* PageToken.

	   page_token
	*/
	PageToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get provisioning v1 tiers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProvisioningV1TiersParams) WithDefaults() *GetProvisioningV1TiersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get provisioning v1 tiers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProvisioningV1TiersParams) SetDefaults() {
	var (
		pageSizeDefault = int64(10)
	)

	val := GetProvisioningV1TiersParams{
		PageSize: &pageSizeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) WithTimeout(timeout time.Duration) *GetProvisioningV1TiersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) WithContext(ctx context.Context) *GetProvisioningV1TiersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) WithHTTPClient(client *http.Client) *GetProvisioningV1TiersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageOrder adds the pageOrder to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) WithPageOrder(pageOrder *string) *GetProvisioningV1TiersParams {
	o.SetPageOrder(pageOrder)
	return o
}

// SetPageOrder adds the pageOrder to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) SetPageOrder(pageOrder *string) {
	o.PageOrder = pageOrder
}

// WithPageSize adds the pageSize to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) WithPageSize(pageSize *int64) *GetProvisioningV1TiersParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithPageToken adds the pageToken to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) WithPageToken(pageToken *string) *GetProvisioningV1TiersParams {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the get provisioning v1 tiers params
func (o *GetProvisioningV1TiersParams) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetProvisioningV1TiersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PageOrder != nil {

		// query param page_order
		var qrPageOrder string

		if o.PageOrder != nil {
			qrPageOrder = *o.PageOrder
		}
		qPageOrder := qrPageOrder
		if qPageOrder != "" {

			if err := r.SetQueryParam("page_order", qPageOrder); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.PageToken != nil {

		// query param page_token
		var qrPageToken string

		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {

			if err := r.SetQueryParam("page_token", qPageToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
