// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// GetProvisioningV1ProductsProductNameConfigsReader is a Reader for the GetProvisioningV1ProductsProductNameConfigs structure.
type GetProvisioningV1ProductsProductNameConfigsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvisioningV1ProductsProductNameConfigsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProvisioningV1ProductsProductNameConfigsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProvisioningV1ProductsProductNameConfigsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProvisioningV1ProductsProductNameConfigsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProvisioningV1ProductsProductNameConfigsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProvisioningV1ProductsProductNameConfigsOK creates a GetProvisioningV1ProductsProductNameConfigsOK with default headers values
func NewGetProvisioningV1ProductsProductNameConfigsOK() *GetProvisioningV1ProductsProductNameConfigsOK {
	return &GetProvisioningV1ProductsProductNameConfigsOK{}
}

/* GetProvisioningV1ProductsProductNameConfigsOK describes a response with status code 200, with default header values.

OK
*/
type GetProvisioningV1ProductsProductNameConfigsOK struct {
	Payload *models.V1ProductConfigResponse
}

func (o *GetProvisioningV1ProductsProductNameConfigsOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/products/{product_name}/configs][%d] getProvisioningV1ProductsProductNameConfigsOK  %+v", 200, o.Payload)
}
func (o *GetProvisioningV1ProductsProductNameConfigsOK) GetPayload() *models.V1ProductConfigResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProductsProductNameConfigsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ProductConfigResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProductsProductNameConfigsBadRequest creates a GetProvisioningV1ProductsProductNameConfigsBadRequest with default headers values
func NewGetProvisioningV1ProductsProductNameConfigsBadRequest() *GetProvisioningV1ProductsProductNameConfigsBadRequest {
	return &GetProvisioningV1ProductsProductNameConfigsBadRequest{}
}

/* GetProvisioningV1ProductsProductNameConfigsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProvisioningV1ProductsProductNameConfigsBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProductsProductNameConfigsBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/products/{product_name}/configs][%d] getProvisioningV1ProductsProductNameConfigsBadRequest  %+v", 400, o.Payload)
}
func (o *GetProvisioningV1ProductsProductNameConfigsBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProductsProductNameConfigsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProductsProductNameConfigsUnauthorized creates a GetProvisioningV1ProductsProductNameConfigsUnauthorized with default headers values
func NewGetProvisioningV1ProductsProductNameConfigsUnauthorized() *GetProvisioningV1ProductsProductNameConfigsUnauthorized {
	return &GetProvisioningV1ProductsProductNameConfigsUnauthorized{}
}

/* GetProvisioningV1ProductsProductNameConfigsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProvisioningV1ProductsProductNameConfigsUnauthorized struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProductsProductNameConfigsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/products/{product_name}/configs][%d] getProvisioningV1ProductsProductNameConfigsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetProvisioningV1ProductsProductNameConfigsUnauthorized) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProductsProductNameConfigsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ProductsProductNameConfigsInternalServerError creates a GetProvisioningV1ProductsProductNameConfigsInternalServerError with default headers values
func NewGetProvisioningV1ProductsProductNameConfigsInternalServerError() *GetProvisioningV1ProductsProductNameConfigsInternalServerError {
	return &GetProvisioningV1ProductsProductNameConfigsInternalServerError{}
}

/* GetProvisioningV1ProductsProductNameConfigsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProvisioningV1ProductsProductNameConfigsInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ProductsProductNameConfigsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/products/{product_name}/configs][%d] getProvisioningV1ProductsProductNameConfigsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetProvisioningV1ProductsProductNameConfigsInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ProductsProductNameConfigsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
