// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// NewPostProvisioningV1ConfigsParams creates a new PostProvisioningV1ConfigsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProvisioningV1ConfigsParams() *PostProvisioningV1ConfigsParams {
	return &PostProvisioningV1ConfigsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProvisioningV1ConfigsParamsWithTimeout creates a new PostProvisioningV1ConfigsParams object
// with the ability to set a timeout on a request.
func NewPostProvisioningV1ConfigsParamsWithTimeout(timeout time.Duration) *PostProvisioningV1ConfigsParams {
	return &PostProvisioningV1ConfigsParams{
		timeout: timeout,
	}
}

// NewPostProvisioningV1ConfigsParamsWithContext creates a new PostProvisioningV1ConfigsParams object
// with the ability to set a context for a request.
func NewPostProvisioningV1ConfigsParamsWithContext(ctx context.Context) *PostProvisioningV1ConfigsParams {
	return &PostProvisioningV1ConfigsParams{
		Context: ctx,
	}
}

// NewPostProvisioningV1ConfigsParamsWithHTTPClient creates a new PostProvisioningV1ConfigsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProvisioningV1ConfigsParamsWithHTTPClient(client *http.Client) *PostProvisioningV1ConfigsParams {
	return &PostProvisioningV1ConfigsParams{
		HTTPClient: client,
	}
}

/* PostProvisioningV1ConfigsParams contains all the parameters to send to the API endpoint
   for the post provisioning v1 configs operation.

   Typically these are written to a http.Request.
*/
type PostProvisioningV1ConfigsParams struct {

	/* Request.

	   Request Body
	*/
	Request *models.V1CreateConfigWithValuesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post provisioning v1 configs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProvisioningV1ConfigsParams) WithDefaults() *PostProvisioningV1ConfigsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post provisioning v1 configs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProvisioningV1ConfigsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post provisioning v1 configs params
func (o *PostProvisioningV1ConfigsParams) WithTimeout(timeout time.Duration) *PostProvisioningV1ConfigsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post provisioning v1 configs params
func (o *PostProvisioningV1ConfigsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post provisioning v1 configs params
func (o *PostProvisioningV1ConfigsParams) WithContext(ctx context.Context) *PostProvisioningV1ConfigsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post provisioning v1 configs params
func (o *PostProvisioningV1ConfigsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post provisioning v1 configs params
func (o *PostProvisioningV1ConfigsParams) WithHTTPClient(client *http.Client) *PostProvisioningV1ConfigsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post provisioning v1 configs params
func (o *PostProvisioningV1ConfigsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post provisioning v1 configs params
func (o *PostProvisioningV1ConfigsParams) WithRequest(request *models.V1CreateConfigWithValuesRequest) *PostProvisioningV1ConfigsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post provisioning v1 configs params
func (o *PostProvisioningV1ConfigsParams) SetRequest(request *models.V1CreateConfigWithValuesRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostProvisioningV1ConfigsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
