// Code generated by go-swagger; DO NOT EDIT.

package get_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetNotificationsV1SubscribersSubscriberIDNotificationsParams creates a new GetNotificationsV1SubscribersSubscriberIDNotificationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNotificationsV1SubscribersSubscriberIDNotificationsParams() *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	return &GetNotificationsV1SubscribersSubscriberIDNotificationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNotificationsV1SubscribersSubscriberIDNotificationsParamsWithTimeout creates a new GetNotificationsV1SubscribersSubscriberIDNotificationsParams object
// with the ability to set a timeout on a request.
func NewGetNotificationsV1SubscribersSubscriberIDNotificationsParamsWithTimeout(timeout time.Duration) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	return &GetNotificationsV1SubscribersSubscriberIDNotificationsParams{
		timeout: timeout,
	}
}

// NewGetNotificationsV1SubscribersSubscriberIDNotificationsParamsWithContext creates a new GetNotificationsV1SubscribersSubscriberIDNotificationsParams object
// with the ability to set a context for a request.
func NewGetNotificationsV1SubscribersSubscriberIDNotificationsParamsWithContext(ctx context.Context) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	return &GetNotificationsV1SubscribersSubscriberIDNotificationsParams{
		Context: ctx,
	}
}

// NewGetNotificationsV1SubscribersSubscriberIDNotificationsParamsWithHTTPClient creates a new GetNotificationsV1SubscribersSubscriberIDNotificationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNotificationsV1SubscribersSubscriberIDNotificationsParamsWithHTTPClient(client *http.Client) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	return &GetNotificationsV1SubscribersSubscriberIDNotificationsParams{
		HTTPClient: client,
	}
}

/* GetNotificationsV1SubscribersSubscriberIDNotificationsParams contains all the parameters to send to the API endpoint
   for the get notifications v1 subscribers subscriber ID notifications operation.

   Typically these are written to a http.Request.
*/
type GetNotificationsV1SubscribersSubscriberIDNotificationsParams struct {

	/* PageColumn.

	   Field on which the records are sorted.
	*/
	PageColumn *string

	/* PageOrder.

	   ASC/DESC
	*/
	PageOrder *string

	/* PageSize.

	   Number of records per page.
	*/
	PageSize *int64

	/* PageToken.

	   Page token to fetch next or previous page.
	*/
	PageToken *string

	/* SubscriberID.

	   subscriber id i.e. user id
	*/
	SubscriberID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get notifications v1 subscribers subscriber ID notifications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WithDefaults() *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get notifications v1 subscribers subscriber ID notifications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WithTimeout(timeout time.Duration) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WithContext(ctx context.Context) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WithHTTPClient(client *http.Client) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageColumn adds the pageColumn to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WithPageColumn(pageColumn *string) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	o.SetPageColumn(pageColumn)
	return o
}

// SetPageColumn adds the pageColumn to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) SetPageColumn(pageColumn *string) {
	o.PageColumn = pageColumn
}

// WithPageOrder adds the pageOrder to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WithPageOrder(pageOrder *string) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	o.SetPageOrder(pageOrder)
	return o
}

// SetPageOrder adds the pageOrder to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) SetPageOrder(pageOrder *string) {
	o.PageOrder = pageOrder
}

// WithPageSize adds the pageSize to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WithPageSize(pageSize *int64) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithPageToken adds the pageToken to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WithPageToken(pageToken *string) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WithSubscriberID adds the subscriberID to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WithSubscriberID(subscriberID string) *GetNotificationsV1SubscribersSubscriberIDNotificationsParams {
	o.SetSubscriberID(subscriberID)
	return o
}

// SetSubscriberID adds the subscriberId to the get notifications v1 subscribers subscriber ID notifications params
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) SetSubscriberID(subscriberID string) {
	o.SubscriberID = subscriberID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNotificationsV1SubscribersSubscriberIDNotificationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PageColumn != nil {

		// query param page_column
		var qrPageColumn string

		if o.PageColumn != nil {
			qrPageColumn = *o.PageColumn
		}
		qPageColumn := qrPageColumn
		if qPageColumn != "" {

			if err := r.SetQueryParam("page_column", qPageColumn); err != nil {
				return err
			}
		}
	}

	if o.PageOrder != nil {

		// query param page_order
		var qrPageOrder string

		if o.PageOrder != nil {
			qrPageOrder = *o.PageOrder
		}
		qPageOrder := qrPageOrder
		if qPageOrder != "" {

			if err := r.SetQueryParam("page_order", qPageOrder); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.PageToken != nil {

		// query param page_token
		var qrPageToken string

		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {

			if err := r.SetQueryParam("page_token", qPageToken); err != nil {
				return err
			}
		}
	}

	// path param subscriber_id
	if err := r.SetPathParam("subscriber_id", o.SubscriberID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
