// Code generated by go-swagger; DO NOT EDIT.

package services_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// GetProvisioningV1ServicesServiceIDSecurityCredentialsReader is a Reader for the GetProvisioningV1ServicesServiceIDSecurityCredentials structure.
type GetProvisioningV1ServicesServiceIDSecurityCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProvisioningV1ServicesServiceIDSecurityCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProvisioningV1ServicesServiceIDSecurityCredentialsOK creates a GetProvisioningV1ServicesServiceIDSecurityCredentialsOK with default headers values
func NewGetProvisioningV1ServicesServiceIDSecurityCredentialsOK() *GetProvisioningV1ServicesServiceIDSecurityCredentialsOK {
	return &GetProvisioningV1ServicesServiceIDSecurityCredentialsOK{}
}

/* GetProvisioningV1ServicesServiceIDSecurityCredentialsOK describes a response with status code 200, with default header values.

OK
*/
type GetProvisioningV1ServicesServiceIDSecurityCredentialsOK struct {
	Payload *models.V1CredentialsResponse
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}/security/credentials][%d] getProvisioningV1ServicesServiceIdSecurityCredentialsOK  %+v", 200, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsOK) GetPayload() *models.V1CredentialsResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1CredentialsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest creates a GetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest with default headers values
func NewGetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest() *GetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest {
	return &GetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest{}
}

/* GetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}/security/credentials][%d] getProvisioningV1ServicesServiceIdSecurityCredentialsBadRequest  %+v", 400, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized creates a GetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized with default headers values
func NewGetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized() *GetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized {
	return &GetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized{}
}

/* GetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}/security/credentials][%d] getProvisioningV1ServicesServiceIdSecurityCredentialsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound creates a GetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound with default headers values
func NewGetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound() *GetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound {
	return &GetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound{}
}

/* GetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}/security/credentials][%d] getProvisioningV1ServicesServiceIdSecurityCredentialsNotFound  %+v", 404, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError creates a GetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError with default headers values
func NewGetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError() *GetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError {
	return &GetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError{}
}

/* GetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/services/{service_id}/security/credentials][%d] getProvisioningV1ServicesServiceIdSecurityCredentialsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
