// Code generated by go-swagger; DO NOT EDIT.

package services_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProvisioningV1ServicesServiceIDSecurityCredentialsParams creates a new GetProvisioningV1ServicesServiceIDSecurityCredentialsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProvisioningV1ServicesServiceIDSecurityCredentialsParams() *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams {
	return &GetProvisioningV1ServicesServiceIDSecurityCredentialsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProvisioningV1ServicesServiceIDSecurityCredentialsParamsWithTimeout creates a new GetProvisioningV1ServicesServiceIDSecurityCredentialsParams object
// with the ability to set a timeout on a request.
func NewGetProvisioningV1ServicesServiceIDSecurityCredentialsParamsWithTimeout(timeout time.Duration) *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams {
	return &GetProvisioningV1ServicesServiceIDSecurityCredentialsParams{
		timeout: timeout,
	}
}

// NewGetProvisioningV1ServicesServiceIDSecurityCredentialsParamsWithContext creates a new GetProvisioningV1ServicesServiceIDSecurityCredentialsParams object
// with the ability to set a context for a request.
func NewGetProvisioningV1ServicesServiceIDSecurityCredentialsParamsWithContext(ctx context.Context) *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams {
	return &GetProvisioningV1ServicesServiceIDSecurityCredentialsParams{
		Context: ctx,
	}
}

// NewGetProvisioningV1ServicesServiceIDSecurityCredentialsParamsWithHTTPClient creates a new GetProvisioningV1ServicesServiceIDSecurityCredentialsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProvisioningV1ServicesServiceIDSecurityCredentialsParamsWithHTTPClient(client *http.Client) *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams {
	return &GetProvisioningV1ServicesServiceIDSecurityCredentialsParams{
		HTTPClient: client,
	}
}

/* GetProvisioningV1ServicesServiceIDSecurityCredentialsParams contains all the parameters to send to the API endpoint
   for the get provisioning v1 services service ID security credentials operation.

   Typically these are written to a http.Request.
*/
type GetProvisioningV1ServicesServiceIDSecurityCredentialsParams struct {

	/* ServiceID.

	   Service ID
	*/
	ServiceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get provisioning v1 services service ID security credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) WithDefaults() *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get provisioning v1 services service ID security credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get provisioning v1 services service ID security credentials params
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) WithTimeout(timeout time.Duration) *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get provisioning v1 services service ID security credentials params
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get provisioning v1 services service ID security credentials params
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) WithContext(ctx context.Context) *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get provisioning v1 services service ID security credentials params
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get provisioning v1 services service ID security credentials params
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) WithHTTPClient(client *http.Client) *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get provisioning v1 services service ID security credentials params
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServiceID adds the serviceID to the get provisioning v1 services service ID security credentials params
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) WithServiceID(serviceID string) *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the get provisioning v1 services service ID security credentials params
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProvisioningV1ServicesServiceIDSecurityCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param service_id
	if err := r.SetPathParam("service_id", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
