// Code generated by go-swagger; DO NOT EDIT.

package services_security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/dps/models"
)

// GetProvisioningV1InternalServicesServiceIDSecurityCredentialsReader is a Reader for the GetProvisioningV1InternalServicesServiceIDSecurityCredentials structure.
type GetProvisioningV1InternalServicesServiceIDSecurityCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK creates a GetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK with default headers values
func NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK() *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK {
	return &GetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK{}
}

/* GetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK describes a response with status code 200, with default header values.

OK
*/
type GetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK struct {
	Payload *models.V1CredentialsResponse
}

func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/internal/services/{service_id}/security/credentials][%d] getProvisioningV1InternalServicesServiceIdSecurityCredentialsOK  %+v", 200, o.Payload)
}
func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK) GetPayload() *models.V1CredentialsResponse {
	return o.Payload
}

func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1CredentialsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest creates a GetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest with default headers values
func NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest() *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest {
	return &GetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest{}
}

/* GetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/internal/services/{service_id}/security/credentials][%d] getProvisioningV1InternalServicesServiceIdSecurityCredentialsBadRequest  %+v", 400, o.Payload)
}
func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound creates a GetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound with default headers values
func NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound() *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound {
	return &GetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound{}
}

/* GetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/internal/services/{service_id}/security/credentials][%d] getProvisioningV1InternalServicesServiceIdSecurityCredentialsNotFound  %+v", 404, o.Payload)
}
func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError creates a GetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError with default headers values
func NewGetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError() *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError {
	return &GetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError{}
}

/* GetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError struct {
	Payload *models.ErrrErrorResponse
}

func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/internal/services/{service_id}/security/credentials][%d] getProvisioningV1InternalServicesServiceIdSecurityCredentialsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError) GetPayload() *models.ErrrErrorResponse {
	return o.Payload
}

func (o *GetProvisioningV1InternalServicesServiceIDSecurityCredentialsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrrErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
