// Code generated by go-swagger; DO NOT EDIT.

package create_channel_email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mariadb-corporation/skysql-api-go/v2/nos/models"
)

// NewPostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams creates a new PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams() *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	return &PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithTimeout creates a new PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams object
// with the ability to set a timeout on a request.
func NewPostNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithTimeout(timeout time.Duration) *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	return &PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams{
		timeout: timeout,
	}
}

// NewPostNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithContext creates a new PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams object
// with the ability to set a context for a request.
func NewPostNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithContext(ctx context.Context) *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	return &PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams{
		Context: ctx,
	}
}

// NewPostNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithHTTPClient creates a new PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostNotificationsV1SubscribersSubscriberIDChannelsEmailsParamsWithHTTPClient(client *http.Client) *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	return &PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams{
		HTTPClient: client,
	}
}

/* PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams contains all the parameters to send to the API endpoint
   for the post notifications v1 subscribers subscriber ID channels emails operation.

   Typically these are written to a http.Request.
*/
type PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams struct {

	/* Request.

	   Request Body
	*/
	Request *models.DtoCreateChannelEmail

	/* SubscriberID.

	   subscriber id i.e. user id
	*/
	SubscriberID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post notifications v1 subscribers subscriber ID channels emails params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithDefaults() *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post notifications v1 subscribers subscriber ID channels emails params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithTimeout(timeout time.Duration) *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithContext(ctx context.Context) *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithHTTPClient(client *http.Client) *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithRequest(request *models.DtoCreateChannelEmail) *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetRequest(request *models.DtoCreateChannelEmail) {
	o.Request = request
}

// WithSubscriberID adds the subscriberID to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WithSubscriberID(subscriberID string) *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams {
	o.SetSubscriberID(subscriberID)
	return o
}

// SetSubscriberID adds the subscriberId to the post notifications v1 subscribers subscriber ID channels emails params
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) SetSubscriberID(subscriberID string) {
	o.SubscriberID = subscriberID
}

// WriteToRequest writes these params to a swagger request
func (o *PostNotificationsV1SubscribersSubscriberIDChannelsEmailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param subscriber_id
	if err := r.SetPathParam("subscriber_id", o.SubscriberID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
